const workHistory = [
  {
    companyName: "Arolytics",
    role: "Fullstack Software Developer",
    duration: "Oct'23 – Oct'24",
    workDes: [
      "Optimized a large-scale React application using styled-components for modular CSS and Redux and Context API for state management, enhancing performance.",
      "Created and optimized APIs using Python Flask, incorporating Redis caching mechanisms for faster data retrieval, reducing response latency by 35% and improving system reliability by 40%.",
      "Deployed web applications to AWS, integrating EC2, AWS Serverless, AWS Lamda and S3 along with CPU utilization alerts, streamlining deployment and enhancing system performance..",
      "Enhanced system efficiency by 25% and reduced large dataset query times by 30% through MongoDB schema design, aggregation framework optimization, and query tuning.",
      "Collaborated with design and product teams to transform business ideas into functional applications, driving core epic development that meets product needs",
      "Conducted peer code reviews on GitHub to uphold quality standards and ensure alignment with strategic goals, leveraging GitHub Actions to automate testing and deployment processes",
      "Created dynamic visualizations for methane emissions using React Query, Mapbox API, DeckGL, and React Charts, boosting data accessibility and engagemen",
      "Implemented automated testing processes using Jest and React Testing Library, resulting in a 40% increase in test coverage and a 25% decrease in bug resolution time"
    ],
    exposer: [
      "React",
      "React Query",
      "Redux",
      "NodeJs",
      "ExpressJs",
      "MongoDB",
      "Amazon Lamda",
      "Amazon AWS",
      "Python",
      "Flask",
      "Redis",
      "Jest",
      "React Testing Library",
      "Mapbox API",
      "DeckGL",
      "React Charts",
      "Styled Components",
    ],
    link: "https://www.arolytics.com/",
  }
  ,
  {
    companyName: "Digimaze",
    role: "Fullstack Software Developer",
    duration: "Aug'22 – March'23",
    workDes: [
      "Collaborated on the user interface using NextJS and delve into React Redux library for state management. Leveraged MongoDB for efficient data storage and retrieval",
      "Utilized NodeJS Micro-service and ExpressJS to create an optimized REST API, significantly enhancing the performance of the company’s Review System project.",
      "Crafted a robust React-based web application, leveraging expertise in HTML, CSS, JQuery, and external JavaScript libraries.",
      "Facilitated training documents using Confluence and provided ongoing support to end-users.",
      "Configured and deployed web applications on Digital Ocean and AWS server, incorporating Amazon Lambda, EC2, and S3 Bucket concepts.",
    ],
    exposer: [
      "React",
      "Next",
      "Redux",
      "NodeJs",
      "ExpressJs",
      "MongoDB",
      "Amazon Lamda",
      "Amazon AWS",
    ],
    link: "https://digimaze.io/",
  },
  {
    companyName: "Infosys Limited",
    role: "Senior System Engineer",
    duration: "Oct'20 – Jul'22",
    workDes: [
      "Engineered microservices with Node.js to build robust and scalable RESTful APIs. Utilized NPM Packages, including MySQL and Mongoose for database interaction retrieval within the application.",
      "Demonstrated proficiency in maintaining a robustAngularframework-based web application codebase, leveraging TypeScript, HTML, CSS, and JavaScript expertise.",
      "Tailored REST APIs for Informatica’s business entity service, enabling streamlined retrieval of extensive data sets.",
      "Managed Java EE based web app codebase, utilizing Core JAVA, JSP, Servlet, JDBC and Oracle and DB2 Database for customized report generation",
      "Configured the Jenkins CI/CD pipeline to automate the deployment of JAVA Builds, reducing deployment time by 50%.",
      "Collaborated on cross-functional migration of legacy data into Informatica MDM via Informatica Data Quality ETL, enhancing data accuracy by 75% for CN Rails and BNSF Railways clients.",
    ],
    exposer: [
      "Informatica MDM ",
      "JAVA",
      "Spring Boot",
      "Apahe Tomcat",
      "Oracle Essbase",
      "Amazon AWS",
      "Node JS",
      "Angular",
      "JAVA EE",
      "React JS",
    ],
    link: "https://www.infosys.com/",
  },
  {
    companyName: "Infosys Limited",
    role: "System Engineer Intern",
    duration: "Jan'20 – Mar'20",
    workDes: [
      "Completed in-depth training in Python,JavaScript Core Java, Data Structures, RDBMS, and PL/SQL.",
      "Created a Python web scraping automation script for a project.",
      "Trained in NodeJS and Java to design and develop microservices and Rest APIs for scalable web applications.",
    ],
    exposer: ["Python", "JAVA", "PL/SQL", "Oracle", "Data Structure"],
    link: "https://www.infosys.com/",
  },
];

export default workHistory;
