const workHistory = [
  {
    companyName: "Arolytics",
    role: "Fullstack Software Developer",
    duration: "Oct'23 – Oct'24",
    workDes: [
      "I played a key part in building a methane emissions analysis platform, crafting user-centric interfaces with React, Redux, styled-components, HTML, CSS, and TailwindCSS. My expertise in GIS and visualization tools, such as React Charts, Mapbox API, and Deck GL, allowed me to deliver insightful visualizations that support critical decision-making for emissions management.",
      "On the back end, I developed robust automation scripts and RESTful APIs with Python, Node.js, and Java, streamlining data processes and enhancing application performance. I also designed efficient NoSQL schemas in MongoDB, optimizing aggregation queries and tuning performance to handle large, complex datasets. By continuously optimizing these data workflows, I ensured quick, accurate data retrieval, further enriching the user experience.",
      "Collaborating closely with cross-functional teams, I iterated on features to align with client objectives and enhance usability. My contributions helped create a responsive, high-impact platform that addresses complex environmental challenges through data transparency and innovative technology.",
      // "Enhanced system efficiency by 25% and reduced large dataset query times by 30% through MongoDB schema design, aggregation framework optimization, and query tuning.",
      // "Collaborated with design and product teams to transform business ideas into functional applications, driving core epic development that meets product needs",
      // "Conducted peer code reviews on GitHub to uphold quality standards and ensure alignment with strategic goals, leveraging GitHub Actions to automate testing and deployment processes",
      // "Created dynamic visualizations for methane emissions using React Query, Mapbox API, DeckGL, and React Charts, boosting data accessibility and engagemen",
      // "Implemented automated testing processes using Jest and React Testing Library, resulting in a 40% increase in test coverage and a 25% decrease in bug resolution time"
    ],
    exposer: [
      "React",
      "React Query",
      "Redux",
      "NodeJs",
      "ExpressJs",
      "MongoDB",
      "Amazon Lamda",
      "Amazon AWS",
      "Python",
      "Flask",
      "Redis",
      "Jest",
      "React Testing Library",
      "Mapbox API",
      "DeckGL",
      "React Charts",
      "Styled Components",
    ],
    link: "https://www.arolytics.com/",
  }
  ,
  {
    companyName: "Digimaze",
    role: "Fullstack Software Developer",
    duration: "Aug'22 – March'23",
    workDes: [
      "At DigiMaze, an early-stage startup, I was instrumental in developing a review referral system aimed at boosting user engagement and brand advocacy. I collaborated on building a dynamic UI with Next.js (React framework), implementing React Redux for efficient state management and MongoDB for seamless data storage and retrieval.",
      "In close collaboration with the design team, I translated Figma prototypes into functional, responsive React components, elevating both the visual appeal and user experience. On the back end, I developed high-performance REST APIs using Java Spring Boot, Node.js microservices with Express.js, and Python Flask. I also incorporated GraphQL APIs via Apollo, optimizing system functionality to support data-driven and scalable features",
       "Configured and deployed web applications on Digital Ocean and AWS server, incorporating Amazon Lambda, EC2, and S3 Bucket concepts.",
      "Through these efforts, I contributed to building a robust, user-centered platform, helping DigiMaze establish a foundation for scalable growth and impactful customer engagement in a fast-paced startup setting",
      // "Facilitated training documents using Confluence and provided ongoing support to end-users.",
     
    ],
    exposer: [
      "React",
      "Next",
      "Redux",
      "NodeJs",
      "ExpressJs",
      "MongoDB",
      "Amazon Lamda",
      "Amazon AWS",
    ],
    link: "https://digimaze.io/",
  },
  {
    companyName: "Infosys Limited",
    role: "Senior System Engineer",
    duration: "Oct'20 – Jul'22",
    workDes: [
      "Engineered microservices with Node.js to build robust and scalable RESTful APIs. Utilized NPM Packages, including MySQL and Mongoose for database interaction retrieval within the application.",
      "Demonstrated proficiency in maintaining a robustAngularframework-based web application codebase, leveraging TypeScript, HTML, CSS, and JavaScript expertise.",
      "Tailored REST APIs for Informatica’s business entity service, enabling streamlined retrieval of extensive data sets.",
      "Managed Java EE based web app codebase, utilizing Core JAVA, JSP, Servlet, JDBC and Oracle and DB2 Database for customized report generation",
      "Configured the Jenkins CI/CD pipeline to automate the deployment of JAVA Builds, reducing deployment time by 50%.",
      "Collaborated on cross-functional migration of legacy data into Informatica MDM via Informatica Data Quality ETL, enhancing data accuracy by 75% for CN Rails and BNSF Railways clients.",
    ],
    exposer: [
      "Informatica MDM ",
      "JAVA",
      "Spring Boot",
      "Apahe Tomcat",
      "Oracle Essbase",
      "Amazon AWS",
      "Node JS",
      "Angular",
      "JAVA EE",
      "React JS",
    ],
    link: "https://www.infosys.com/",
  },
  {
    companyName: "Infosys Limited",
    role: "System Engineer Intern",
    duration: "Jan'20 – Mar'20",
    workDes: [
      "Completed in-depth training in Python,JavaScript Core Java, Data Structures, RDBMS, and PL/SQL.",
      "Created a Python web scraping automation script for a project.",
      "Trained in NodeJS and Java to design and develop microservices and Rest APIs for scalable web applications.",
    ],
    exposer: ["Python", "JAVA", "PL/SQL", "Oracle", "Data Structure"],
    link: "https://www.infosys.com/",
  },
];

export default workHistory;
